# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReplGo < Formula
  desc "Add more read-eval-print-love in your life"
  homepage "https://github.com/citizen428/repl"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/citizen428/repl/releases/download/v1.0.1/repl_1.0.1_macOS_arm64.tar.gz"
      sha256 "65a3b7acb109018f26bce2b0ac18fc40ed20231378066d8631e01fdd8e202fc3"

      def install
        bin.install "repl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/citizen428/repl/releases/download/v1.0.1/repl_1.0.1_macOS_x86_64.tar.gz"
      sha256 "de673d2403b4586775cb6ef49adc22635190a33cd79bbf9a2950199d94d5f960"

      def install
        bin.install "repl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/citizen428/repl/releases/download/v1.0.1/repl_1.0.1_Linux_arm64.tar.gz"
      sha256 "b0f29cf9eacb9204f6c7b506dc2c5e3df5d34437031ae2d86dc5bcda14bb1151"

      def install
        bin.install "repl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/citizen428/repl/releases/download/v1.0.1/repl_1.0.1_Linux_x86_64.tar.gz"
      sha256 "d454deaed1bd191a0e42447d622ddf0a45a2b4aef4cb87620aaea0928d03707e"

      def install
        bin.install "repl"
      end
    end
  end
end
