# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReplGo < Formula
  desc "Add more read-eval-print-love in your life"
  homepage "https://github.com/citizen428/repl"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/citizen428/repl/releases/download/v1.0.2/repl_1.0.2_macOS_arm64.tar.gz"
      sha256 "d201af87bea73371e9f3793aa85b1fca0d350c417aa344aa71e94704a75c567e"

      def install
        bin.install "repl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/citizen428/repl/releases/download/v1.0.2/repl_1.0.2_macOS_x86_64.tar.gz"
      sha256 "951a0593ec6d706fc27b4235fed0c8d7fd64bf0d5770516eaafc5c5a7e0b8d4a"

      def install
        bin.install "repl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/citizen428/repl/releases/download/v1.0.2/repl_1.0.2_Linux_arm64.tar.gz"
      sha256 "f78c5e3cb4fdc059e6af74c470899717b836ad97a5b46717389993266313ed40"

      def install
        bin.install "repl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/citizen428/repl/releases/download/v1.0.2/repl_1.0.2_Linux_x86_64.tar.gz"
      sha256 "0e3fb64e8f02743bcec25b4f61cf53ac4f97760165837dd8a429647e7cb4bbd7"

      def install
        bin.install "repl"
      end
    end
  end
end
